all:
	epstopdf architecture-lexsel.eps
	dot -Teps transducer.dot -otransducer.eps
	dot -Teps transducer2.dot -otransducer2.eps
	dot -Teps transducer3.dot -otransducer3.eps
	xelatex 2015-eamt-melsa-poster.tex
