all:
	pdflatex finnormal2015.tex
	bibtex finnormal2015
	pdflatex finnormal2015.tex
	pdflatex finnormal2015.tex

clean:
	rm finnormal2015.aux finnormal2015.bbl finnormal2015.blg finnormal2015.log finnormal2015.pdf texput.log 
