all:
	pdflatex 2015-eamt-assim.tex
	bibtex 2015-eamt-assim
	pdflatex 2015-eamt-assim.tex
	pdflatex 2015-eamt-assim.tex

clean:
	rm -f 2015-eamt-assim.aux 2015-eamt-assim.bbl 2015-eamt-assim.blg 2015-eamt-assim.log
